### ISSUE TITLE
SQLite3 error

### ISSUE THREAD

**Issue by Lemez** [hilarysk/string_to_ipa#1]
Excited to find this gem, but sadly got this error on first loading.
Am using with Sinatra in a little Ruby app.

SQLite3::SQLException at /
no such table: phonetics
file: database.rb location: initialize line: 91

**Comment by hilarysk** [comment]
Well, that's not supposed to happen!

I'm heading out of town Thursday, but I'll try to take a look before I
leave. Otherwise I'll get on it first-thing next week. Thanks for letting
me know!

**Comment by Lemez** [comment]
Ok thanks. Perhaps the database dependency needs to be loaded independently?

**Comment by ghost** [comment]
I am so blessed to have found your gem! The db reference as proposed by Lemez and the addressed by gadtfly worked great, though is not included in the "gem install string_to_ipa" command when executed from the terminal.
Also, what is best practice to add new words to the db?

**Comment by hilarysk** [comment]
@dpears Good question. At this point, the plan is to simply update it periodically as Carnegie Mellon updates theirs (http://www.speech.cs.cmu.edu/cgi-bin/cmudict) so that I have some guarantee of data integrity.
